# Use an official OpenJDK runtime as a parent image
FROM eclipse-temurin:21-jdk-jammy

# Set the working directory in the container
WORKDIR /app

# Define build path to ./
ARG PROJECT_PATH=./

# Copy the build.gradle and settings.gradle files
COPY ${PROJECT_PATH}/build.gradle.kts ${PROJECT_PATH}/settings.gradle.kts ${PROJECT_PATH}/gradlew ${PROJECT_PATH}/gradlew.bat ./

# Copy the source code
COPY ${PROJECT_PATH}/src ./src

# Copy the gradle directory
COPY ${PROJECT_PATH}/gradle ./gradle

# Copy the run_tests.sh script
COPY ${PROJECT_PATH}/run_tests.sh ./run_tests.sh

# Set the permissions for the gradlew file and the shell script
RUN chmod -R 777 /app

# Set the entry point to the run_tests.sh script
ENTRYPOINT ["./run_tests.sh"]
