
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      env_file: .env
    image: app:latest
    ports:
      ${MS_PORT}:${MS_PORT}
    networks:
      iwa_network
    
  tests: 
    build:
      context: .
      dockerfile: ../cicd/Dockerfile.test
      env_file: .env
    image: tests:latest
networks:
  iwa_network:
    external: true