services:
  app:
    container_name: ${MS_NAME}
    image: ${MS_NAME}-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${MS_PORT}:${MS_PORT}
    environment:
      - DB_URL=jdbc:${DB_TYPE}://${DB_HOST}:${DB_PORT}/${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - API_GATEWAY_URL=${API_GATEWAY_PROTOCOL}://${API_GATEWAY_HOST}:${API_GATEWAY_PORT}
      - MS_NAME=${MS_NAME}
      - MS_PORT=${MS_PORT}
    depends_on:
      - db
    networks:
      - iwa_network
      - default

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - default

  tests:
    container_name: ${MS_NAME}-tests
    image: ${MS_NAME}-tests:latest
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - DB_URL=jdbc:${DB_TYPE}://${DB_HOST}:${DB_PORT}/${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - API_GATEWAY_URL=${API_GATEWAY_PROTOCOL}://${API_GATEWAY_HOST}:${API_GATEWAY_PORT}
      - MS_NAME=${MS_NAME}
      - MS_PORT=${MS_PORT}
    depends_on:
      - db
    networks:
      - iwa_network
      - default


networks:
  # Inter MS communication
  iwa_network:
    external: true
  # Conection to bd
  default:
volumes:
  pgdata:
