# Use an official OpenJDK runtime as a parent image
FROM docker.io/nicolasgoyon/run_spring_tests

# Set the working directory in the container
WORKDIR /app

# Define environment variables
ARG DB_URL
ARG DB_USERNAME
ARG DB_PASSWORD
ARG API_GATEWAY_URL
ARG MS_NAME
ARG MS_PORT
ARG SPRING_KAFKA_BOOTSTRAP_SERVERS_HOST
ARG SPRING_KAFKA_BOOTSTRAP_SERVERS_PORT
ARG SPRING_KAFKA_CONSUMER_GROUP_ID
ARG SPRING_KAFKA_TOPIC_NAME

# General environment variables
ENV DB_URL=${DB_URL}
ENV DB_USERNAME=${DB_USERNAME}
ENV DB_PASSWORD=${DB_PASSWORD}
ENV API_GATEWAY_URL=${API_GATEWAY_URL}
ENV MS_NAME=${MS_NAME}
ENV MS_PORT=${MS_PORT}
ENV SPRING_KAFKA_BOOTSTRAP_SERVERS_HOST=${SPRING_KAFKA_BOOTSTRAP_SERVERS_HOST}
ENV SPRING_KAFKA_BOOTSTRAP_SERVERS_PORT=${SPRING_KAFKA_BOOTSTRAP_SERVERS_PORT}
ENV SPRING_KAFKA_CONSUMER_GROUP_ID=${SPRING_KAFKA_CONSUMER_GROUP_ID}
ENV SPRING_KAFKA_TOPIC_NAME=${SPRING_KAFKA_TOPIC_NAME}

# Define build path to ./
ARG PROJECT_PATH=./

# Copy the build.gradle and settings.gradle files
COPY ${PROJECT_PATH}/build.gradle.kts ${PROJECT_PATH}/settings.gradle.kts ${PROJECT_PATH}/gradlew ${PROJECT_PATH}/gradlew.bat ./

# Copy the source code
COPY ${PROJECT_PATH}/src ./src

# Copy the gradle directory
COPY ${PROJECT_PATH}/gradle ./gradle

# Set the permissions for the gradlew file and the shell script
RUN chmod -R 777 /app