services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - DB_URL=jdbc:${DB_TYPE}://${DB_HOST}:${DB_PORT}/${DB_NAME}
        - DB_USERNAME=${DB_USERNAME}
        - DB_PASSWORD=${DB_PASSWORD}
        - API_GATEWAY_URL=${API_GATEWAY_PROTOCOL}://${API_GATEWAY_HOST}:${API_GATEWAY_PORT}
        - MS_NAME=${MS_NAME}
        - MS_PORT=${MS_PORT}
        - SPRING_KAFKA_BOOTSTRAP_SERVERS_HOST=${SPRING_KAFKA_BOOTSTRAP_SERVERS_HOST}
        - SPRING_KAFKA_BOOTSTRAP_SERVERS_PORT=${SPRING_KAFKA_BOOTSTRAP_SERVERS_PORT}
        - SPRING_KAFKA_CONSUMER_GROUP_ID=${SPRING_KAFKA_CONSUMER_GROUP_ID}
        - SPRING_KAFKA_TOPIC_NAME=${SPRING_KAFKA_TOPIC_NAME}
    ports:
      - ${MS_PORT}:${MS_PORT}
    depends_on:
      - db
    networks:
      - iwa_network
      - default

  db:
    container_name: ${MS_NAME}-db
    build: 
      context: .
      dockerfile: ../cicd/Dockerfile.db
      args:
        POSTGRES_DB: ${DB_NAME}
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - default

  tests:
    build:
      context: .
      dockerfile: ./Dockerfile.test
      args:
        - DB_URL=jdbc:${DB_TYPE}://${DB_HOST}:${DB_PORT}/${DB_NAME}
        - DB_USERNAME=${DB_USERNAME}
        - DB_PASSWORD=${DB_PASSWORD}
        - API_GATEWAY_URL=${API_GATEWAY_PROTOCOL}://${API_GATEWAY_HOST}:${API_GATEWAY_PORT}
        - MS_NAME=${MS_NAME}
        - MS_PORT=${MS_PORT}
        - SPRING_KAFKA_BOOTSTRAP_SERVERS_HOST=${SPRING_KAFKA_BOOTSTRAP_SERVERS_HOST}
        - SPRING_KAFKA_BOOTSTRAP_SERVERS_PORT=${SPRING_KAFKA_BOOTSTRAP_SERVERS_PORT}
        - SPRING_KAFKA_CONSUMER_GROUP_ID=${SPRING_KAFKA_CONSUMER_GROUP_ID}
        - SPRING_KAFKA_TOPIC_NAME=${SPRING_KAFKA_TOPIC_NAME}
    environment:
    - DB_URL=jdbc:${DB_TYPE}://${DB_HOST}:${DB_PORT}/${DB_NAME}
    - DB_USERNAME=${DB_USERNAME}
    - DB_PASSWORD=${DB_PASSWORD}
    - API_GATEWAY_URL=${API_GATEWAY_PROTOCOL}://${API_GATEWAY_HOST}:${API_GATEWAY_PORT}
    - MS_NAME=${MS_NAME}
    - MS_PORT=${MS_PORT}
    - SPRING_KAFKA_BOOTSTRAP_SERVERS_HOST=${SPRING_KAFKA_BOOTSTRAP_SERVERS_HOST}
    - SPRING_KAFKA_BOOTSTRAP_SERVERS_PORT=${SPRING_KAFKA_BOOTSTRAP_SERVERS_PORT}
    - SPRING_KAFKA_CONSUMER_GROUP_ID=${SPRING_KAFKA_CONSUMER_GROUP_ID}
    - SPRING_KAFKA_TOPIC_NAME=${SPRING_KAFKA_TOPIC_NAME}
    depends_on:
      - db
    volumes:
      - ./reports:/app/reports
    networks:
      - iwa_network
      - default


networks:
  # Inter MS communication
  iwa_network:
    external: true
  # Conection to bd
  default: