name: API_GATEWAY CI/CD Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

env:
  JAVA_VERSION: '21'
  PROJECT_PATH: api_gateway
  MICROSERVICE_NAME: api_gateway

jobs:
  wait-for-workflows:
    runs-on: ubuntu-latest
    steps:
    - name: Wait on User Microservice CI/CD
      uses: lucasssvaz/wait-on-workflow@v1
      with:
        workflow: "cicd-ms-user.yml"
        max-wait: 3
        interval: 5
        timeout: 600
        sha: ${{ github.event.pull_request.head.sha || github.sha }}
      
    - name: Wait on Location Microservice CI/CD
      uses: lucasssvaz/wait-on-workflow@v1
      with:
        workflow: "cicd-ms-location.yml"
        max-wait: 3
        interval: 5
        timeout: 600
        sha: ${{ github.event.pull_request.head.sha || github.sha }}

    - name: Wait on Notification Microservice CI/CD
      uses: lucasssvaz/wait-on-workflow@v1
      with:
        workflow: "cicd-ms-notification.yml"
        max-wait: 3
        interval: 5
        timeout: 600
        sha: ${{ github.event.pull_request.head.sha || github.sha }}

    - name: Wait on Reservation Microservice CI/CD
      uses: lucasssvaz/wait-on-workflow@v1
      with:
        workflow: "cicd-ms-reservation.yml"
        max-wait: 3
        interval: 5
        timeout: 600
        sha: ${{ github.event.pull_request.head.sha || github.sha }}




  build-and-test:
    runs-on: ubuntu-latest
    # Depends on : "on-success" job of all microservices
    needs: wait-for-workflows

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install docker-compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Create a network
      run: docker network create iwa_network 

    - name: run docker-compose of db and tests
      run: |
        cd ${{ env.PROJECT_PATH }}
        docker-compose -f tests.docker-compose.yml up --build tests

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.MICROSERVICE_NAME }}-tests-reports
        path: ${{ env.PROJECT_PATH }}/reports

    - name: Clean up
      run: |
        cd ${{ env.PROJECT_PATH }}
        docker-compose -f docker-compose.yml down

  build-and-push:
    runs-on: ubuntu-22.04
    needs: build-and-test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install docker-compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build Docker images using Docker Compose
      run: |
        cd ${{ env.PROJECT_PATH }}
        docker-compose -f docker-compose.yml build app

    - name: Tag Docker images
      run: |
        docker tag app ghcr.io/${{ github.repository_owner }}/${{ env.MICROSERVICE_NAME }}-app:latest

    - name: Push Docker images to GitHub Container Registry
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

        # Push the application image
        docker push ghcr.io/${{ github.repository_owner }}/${{ env.MICROSERVICE_NAME }}-app:latest