name: API_GATEWAY CI/CD Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

env:
  JAVA_VERSION: '21'
  PROJECT_PATH: api_gateway
  MICROSERVICE_NAME: api_gateway

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
          cd ${{ env.PROJECT_PATH }}
          docker build -t testing_image:latest -f Dockerfile.test .

    - name: Run tests
      run: |
          docker run --name testing_container --env-file .env testing_image:latest
          docker cp testing_container:/app/reports ./reports
          docker rm testing_container

    - name: Upload test reports
      uses: actions/upload-artifact@v3
      with:
          name: test-reports
          path: ./reports

    - name: Clean up
      run: docker rmi my-app:latest

  build:
    runs-on: ubuntu-22.04
    needs: build-and-test

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ env.JAVA_VERSION }}

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Change permissions for gradlew
      run: chmod +x ${{ env.PROJECT_PATH }}/gradlew

    - name: Build JAR file
      run: cd ${{ env.PROJECT_PATH }} && ./gradlew clean build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.MICROSERVICE_NAME }}-build
        path: ${{ env.PROJECT_PATH }}/build/libs/*.jar

  deploy:
    runs-on: ubuntu-22.04
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: ${{ env.MICROSERVICE_NAME }}-build
        path: ${{ env.PROJECT_PATH }}/build/libs

    - name: Deploy to test environment
      run: |
        # Add your deployment commands here
        # For example, if you are deploying to a Kubernetes cluster:
        # kubectl apply -f deployment.yaml
        echo "Deploying MS1 to test environment..."
