name: MS_NOTIFICATION CI/CD Pipeline

on:
  push:
    branches:
      - '**'
    paths:
      - 'ms_notification/**'
      - '.github/workflows/cicd-ms-notification.yml'
  pull_request:
    branches:
      - '**'
    paths:
        - 'ms_notification/**'
        - '.github/workflows/cicd-ms-notification.yml'

env:
  JAVA_VERSION: '21'
  PROJECT_PATH: ms_notification
  MICROSERVICE_NAME: ms_notification

jobs:
    
    # wait-for-kafka:
    #   runs-on: ubuntu-latest
    #   steps:
    #     - name: Wait on User Microservice CI/CD
    #       uses: lucasssvaz/wait-on-workflow@v1
    #       with:
    #           workflow: "cicd-kafka.yml"
    #           max-wait: 3
    #           interval: 5
    #           timeout: 600
    #           sha: ${{ github.event.pull_request.head.sha || github.sha }}
      
    build-and-test:
      runs-on: ubuntu-latest
      # needs: wait-for-kafka
  
      steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
  
      - name: Create a network
        run: docker network create iwa_network

      - name: Run tests
        run: |
          cd ${{ env.PROJECT_PATH }}
          docker-compose -f docker-compose.yml up --build --exit-code-from tests tests

      - name: Wait for tests to finish
        run: |
          cd ${{ env.PROJECT_PATH }}
          docker-compose -f docker-compose.yml logs -f tests

      - name: Log the database container
        run: |
          cd ${{ env.PROJECT_PATH }}
          docker-compose -f docker-compose.yml logs db

      - name: List files in ./reports depth = 2
        run: |
          cd ${{ env.PROJECT_PATH }}
          ls -R ./reports

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ env.MICROSERVICE_NAME }}-tests-reports
          path: ${{ env.PROJECT_PATH }}/reports

      - name: Clean up
        run: |
          cd ${{ env.PROJECT_PATH }}
          docker-compose -f docker-compose.yml down

    build-and-push:
      runs-on: ubuntu-22.04
      needs: build-and-test
  
      steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
  
      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
  
      - name: Build Docker images using Docker Compose
        run: |
          cd ${{ env.PROJECT_PATH }}
          docker-compose -f docker-compose.yml build app
          docker-compose -f docker-compose.yml build db 
  
      - name: List Docker images
        run: docker images

      - name: Tag App Docker image
        run: docker tag ${{ env.MICROSERVICE_NAME }}_app ghcr.io/${{ secrets.PACKAGE_OWNER }}/${{ env.MICROSERVICE_NAME }}-app:latest
          
      - name: Tag db Docker image
        run: docker tag ${{ env.MICROSERVICE_NAME }}_db ghcr.io/${{ secrets.PACKAGE_OWNER }}/${{ env.MICROSERVICE_NAME }}-db:latest
  
      - name: Push Docker images to GitHub Container Registry
        run: |
          echo ${{ secrets.PACKAGE_TOKEN }} | docker login ghcr.io -u ${{ secrets.PACKAGE_OWNER }} --password-stdin
  
          docker push ghcr.io/${{ secrets.PACKAGE_OWNER }}/${{ env.MICROSERVICE_NAME }}-app:latest
          docker push ghcr.io/${{ secrets.PACKAGE_OWNER }}/${{ env.MICROSERVICE_NAME }}-db:latest